package controllers

import (
	"math"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/jinzhu/copier"
	"github.com/rizqizyd/project-management-be/models"
	"github.com/rizqizyd/project-management-be/services"
	"github.com/rizqizyd/project-management-be/utils"
)

type UserController struct {
	service services.UserService
}

func NewUserController(s services.UserService) *UserController {
	return &UserController{service: s}
}

func (c *UserController) Register(ctx *fiber.Ctx) error {
	user := new(models.User)

	if err := ctx.BodyParser(user); err != nil {
		return utils.BadRequest(ctx, "Invalid request body", err.Error())
	}

	if err := c.service.Register(user); err != nil {
		return utils.BadRequest(ctx, "Registration failed", err.Error())
	}

	var userResp models.UserResponse
	_ = copier.Copy(&userResp, &user)
	return utils.Success(ctx, "User registered successfully", userResp)
}

func (c *UserController) Login(ctx *fiber.Ctx) error {
	// Generated by Copilot - login functionality is currently commented out.
	// type LoginRequest struct {
	// 	Email    string `json:"email"`
	// 	Password string `json:"password"`
	// }

	// loginReq := new(LoginRequest)

	// if err := ctx.BodyParser(loginReq); err != nil {
	// 	return utils.BadRequest(ctx, "Invalid request body", err.Error())
	// }

	// user, err := c.service.Login(loginReq.Email, loginReq.Password)
	// if err != nil {
	// 	return utils.Unauthorized(ctx, "Login failed", err.Error())
	// }

	// var userResp models.UserResponse
	// _ = copier.Copy(&userResp, &user)
	// return utils.Success(ctx, "User logged in successfully", userResp)

	var body struct {
		Email    string `json:"email"`
		Password string `json:"password"`
	}
	if err := ctx.BodyParser(&body); err != nil {
		return utils.BadRequest(ctx, "Invalid request body", err.Error())
	}

	user, err := c.service.Login(body.Email, body.Password)
	if err != nil {
		return utils.Unauthorized(ctx, "Login failed", err.Error())
	}

	token, _ := utils.GenerateToken(user.InternalID, user.Role, user.Email, user.PublicID)
	refreshToken, _ := utils.GenerateRefreshToken(user.InternalID)

	var userResp models.UserResponse
	_ = copier.Copy(&userResp, &user)

	data := fiber.Map{
		"access_token":  token,
		"refresh_token": refreshToken,
		"user":          userResp,
	}

	return utils.Success(ctx, "User logged in successfully", data)
}

func (c *UserController) GetUser(ctx *fiber.Ctx) error {
	id := ctx.Params("id")
	user, err := c.service.GetByPublicID(id)
	if err != nil {
		return utils.NotFound(ctx, "User not found", err.Error())
	}

	var userResp models.UserResponse
	err = copier.Copy(&userResp, &user)
	if err != nil {
		return utils.BadRequest(ctx, "Internal server error", err.Error())
	}

	return utils.Success(ctx, "User fetched successfully", userResp)
}

func (c *UserController) GetUserPagination(ctx *fiber.Ctx) error {
	// example: /users/page?page=1&limit=10&filter=john&sort=-id
	page, _ := strconv.Atoi(ctx.Query("page", "1"))
	limit, _ := strconv.Atoi(ctx.Query("limit", "10"))
	filter := ctx.Query("filter", "")
	sort := ctx.Query("sort", "-id")

	offset := (page - 1) * limit

	users, total, err := c.service.GetAllPagination(filter, sort, limit, offset)
	if err != nil {
		return utils.BadRequest(ctx, "Failed to fetch users", err.Error())
	}

	var userResp []models.UserResponse
	_ = copier.Copy(&userResp, &users)

	meta := utils.PaginationMeta{
		Page:       page,
		Limit:      limit,
		Total:      int(total),
		TotalPages: int(math.Ceil(float64(total) / float64(limit))),
		Filter:     filter,
		Sort:       sort,
	}

	if total == 0 {
		return utils.NotFoundPagination(ctx, "No users found", userResp, meta)
	}

	return utils.SuccessPagination(ctx, "Users fetched successfully", userResp, meta)
}
